import localFont from "next/font/local";
import { UserProvider } from "@/contextApi/UserContext";
import { CategoryProvider } from "@/contextApi/CategoriesContext";
import { ThemeProvider } from "@/contextApi/ThemeContext";
import { ProductProvider } from "@/contextApi/ProductContext";
import Navbar from "@/components/header/Navbar";
import Sidebar from "@/components/header/Sidebar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <CategoryProvider>
            <UserProvider>
              <ProductProvider>
                <Navbar />
                <Sidebar />
                <main className="bg-gray-100 pt-24">{children}</main>
              </ProductProvider>
            </UserProvider>
          </CategoryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
