import localFont from "next/font/local";
import { UserProvider } from "@/contextApi/UserContext";
import { SidebarProvider } from "@/contextApi/SidebarContext";
import { ThemeProvider } from "@/contextApi/ThemeContext";
import { ProductProvider } from "@/contextApi/ProductContext";
import Navbar from "@/components/header/Navbar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <UserProvider>
            <ProductProvider>
              <SidebarProvider>
                <Navbar />
                {children}
              </SidebarProvider>
            </ProductProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
